# Generated by Django 5.0.4 on 2024-04-27 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_cartitem_quantity'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(max_length=255)),
                ('message', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='trainer',
            name='price_10_session',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='trainer',
            name='price_1_session',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='trainer',
            name='price_5_session',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
