# Generated by Django 5.0.4 on 2024-04-27 12:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_contract_trainer_price_10_session_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Contract',
            new_name='Contact',
        ),
    ]
